version: '3.8'

services:
  # Main presentation website
  presentation:
    build:
      context: ..
      dockerfile: docker/Dockerfile.presentation
    ports:
      - "9000:9000"
    volumes:
      - ../presentation:/app/presentation
    environment:
      - FLASK_ENV=development
    networks:
      - sdnhoney

  # Live demo server with Docker support
  live-demo:
    build:
      context: ..
      dockerfile: docker/Dockerfile.live-demo
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/app
    privileged: true
    environment:
      - FLASK_ENV=development
    networks:
      - sdnhoney
    depends_on:
      - presentation

  # Demo environment container (managed by live-demo service)
  demo-environment:
    build:
      context: ..
      dockerfile: docker/Dockerfile.demo
    ports:
      - "18001:8001"  # h1 service
      - "18002:8002"  # h2 service  
      - "18003:8003"  # h3 service
      - "18004:8004"  # h4 triage honeypot
      - "18005:8005"  # h5 deep honeypot
      - "18080:8080"  # Controller REST API
      - "16653:6653"  # SDN Controller
    privileged: true
    networks:
      - sdnhoney
    profiles:
      - demo  # This will be started/stopped by live-demo service

networks:
  sdnhoney:
    driver: bridge 