# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml_model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ml_model.proto',
  package='ml_model',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eml_model.proto\x12\x08ml_model\"\xbf\x01\n\nPacketInfo\x12\x0e\n\x06src_ip\x18\x01 \x01(\t\x12\x0e\n\x06\x64st_ip\x18\x02 \x01(\t\x12\x10\n\x08src_port\x18\x03 \x01(\x05\x12\x10\n\x08\x64st_port\x18\x04 \x01(\x05\x12\x10\n\x08protocol\x18\x05 \x01(\t\x12\x0f\n\x07service\x18\x06 \x01(\t\x12\x16\n\x0epayload_length\x18\x07 \x01(\x05\x12\x10\n\x08\x64uration\x18\x08 \x01(\x01\x12\x0f\n\x07payload\x18\t \x01(\t\x12\x0f\n\x07\x63ommand\x18\n \x01(\t\"O\n\x12PredictionResponse\x12\x15\n\ris_suspicious\x18\x01 \x01(\x08\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x12\x0e\n\x06reason\x18\x03 \x01(\t\"\x11\n\x0fTrainingRequest\"O\n\x10TrainingResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x19\n\x11samples_processed\x18\x03 \x01(\x05\x32\x9e\x01\n\x0eMLModelService\x12\x45\n\rPredictPacket\x12\x14.ml_model.PacketInfo\x1a\x1c.ml_model.PredictionResponse\"\x00\x12\x45\n\nTrainModel\x12\x19.ml_model.TrainingRequest\x1a\x1a.ml_model.TrainingResponse\"\x00\x62\x06proto3'
)




_PACKETINFO = _descriptor.Descriptor(
  name='PacketInfo',
  full_name='ml_model.PacketInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='src_ip', full_name='ml_model.PacketInfo.src_ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dst_ip', full_name='ml_model.PacketInfo.dst_ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='src_port', full_name='ml_model.PacketInfo.src_port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dst_port', full_name='ml_model.PacketInfo.dst_port', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='protocol', full_name='ml_model.PacketInfo.protocol', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='service', full_name='ml_model.PacketInfo.service', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload_length', full_name='ml_model.PacketInfo.payload_length', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration', full_name='ml_model.PacketInfo.duration', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='ml_model.PacketInfo.payload', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='ml_model.PacketInfo.command', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=220,
)


_PREDICTIONRESPONSE = _descriptor.Descriptor(
  name='PredictionResponse',
  full_name='ml_model.PredictionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_suspicious', full_name='ml_model.PredictionResponse.is_suspicious', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='ml_model.PredictionResponse.confidence', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reason', full_name='ml_model.PredictionResponse.reason', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=301,
)


_TRAININGREQUEST = _descriptor.Descriptor(
  name='TrainingRequest',
  full_name='ml_model.TrainingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=320,
)


_TRAININGRESPONSE = _descriptor.Descriptor(
  name='TrainingResponse',
  full_name='ml_model.TrainingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='ml_model.TrainingResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='ml_model.TrainingResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='samples_processed', full_name='ml_model.TrainingResponse.samples_processed', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=401,
)

DESCRIPTOR.message_types_by_name['PacketInfo'] = _PACKETINFO
DESCRIPTOR.message_types_by_name['PredictionResponse'] = _PREDICTIONRESPONSE
DESCRIPTOR.message_types_by_name['TrainingRequest'] = _TRAININGREQUEST
DESCRIPTOR.message_types_by_name['TrainingResponse'] = _TRAININGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PacketInfo = _reflection.GeneratedProtocolMessageType('PacketInfo', (_message.Message,), {
  'DESCRIPTOR' : _PACKETINFO,
  '__module__' : 'ml_model_pb2'
  # @@protoc_insertion_point(class_scope:ml_model.PacketInfo)
  })
_sym_db.RegisterMessage(PacketInfo)

PredictionResponse = _reflection.GeneratedProtocolMessageType('PredictionResponse', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTIONRESPONSE,
  '__module__' : 'ml_model_pb2'
  # @@protoc_insertion_point(class_scope:ml_model.PredictionResponse)
  })
_sym_db.RegisterMessage(PredictionResponse)

TrainingRequest = _reflection.GeneratedProtocolMessageType('TrainingRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRAININGREQUEST,
  '__module__' : 'ml_model_pb2'
  # @@protoc_insertion_point(class_scope:ml_model.TrainingRequest)
  })
_sym_db.RegisterMessage(TrainingRequest)

TrainingResponse = _reflection.GeneratedProtocolMessageType('TrainingResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAININGRESPONSE,
  '__module__' : 'ml_model_pb2'
  # @@protoc_insertion_point(class_scope:ml_model.TrainingResponse)
  })
_sym_db.RegisterMessage(TrainingResponse)



_MLMODELSERVICE = _descriptor.ServiceDescriptor(
  name='MLModelService',
  full_name='ml_model.MLModelService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=404,
  serialized_end=562,
  methods=[
  _descriptor.MethodDescriptor(
    name='PredictPacket',
    full_name='ml_model.MLModelService.PredictPacket',
    index=0,
    containing_service=None,
    input_type=_PACKETINFO,
    output_type=_PREDICTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TrainModel',
    full_name='ml_model.MLModelService.TrainModel',
    index=1,
    containing_service=None,
    input_type=_TRAININGREQUEST,
    output_type=_TRAININGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MLMODELSERVICE)

DESCRIPTOR.services_by_name['MLModelService'] = _MLMODELSERVICE

# @@protoc_insertion_point(module_scope)
