# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_model.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ml_model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eml_model.proto\x12\x08ml_model\"b\n\nPacketInfo\x12\x0e\n\x06src_ip\x18\x01 \x01(\t\x12\x0e\n\x06\x64st_ip\x18\x02 \x01(\t\x12\x10\n\x08src_port\x18\x03 \x01(\x05\x12\x10\n\x08\x64st_port\x18\x04 \x01(\x05\x12\x10\n\x08protocol\x18\x05 \x01(\t\"#\n\nPrediction\x12\x15\n\ris_suspicious\x18\x01 \x01(\x05\x32M\n\x0eMLModelService\x12;\n\rPredictPacket\x12\x14.ml_model.PacketInfo\x1a\x14.ml_model.Predictionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PACKETINFO']._serialized_start=28
  _globals['_PACKETINFO']._serialized_end=126
  _globals['_PREDICTION']._serialized_start=128
  _globals['_PREDICTION']._serialized_end=163
  _globals['_MLMODELSERVICE']._serialized_start=165
  _globals['_MLMODELSERVICE']._serialized_end=242
# @@protoc_insertion_point(module_scope)
